### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by Mo-Gul**
and improve some formatting/style.

### CODE REVIEW

**Comment by Mo-Gul** [comment]
Other things can be harmonized as well, e.g. the use of `d` in `\int ... dx`. There is one instance of an upright `d`

https://github.com/ClapeyronThermo/Clapeyron.jl/blob/529af13b80647402253f97af317d1be9e851ba09/docs/src/theory/background.md?plain=1#L29

The other (five) instances (just) use the normal math `d` (italics).

**Review by longemen3000 — APPROVED** [review]

**Comment by longemen3000** [comment]
Thanks!
on the use of italics vs upright d, feel free to add those changes here or in another PR. I'm going to merge this tomorrow.

**Comment by Mo-Gul** [comment]
What I have also noticed is that you (sometimes) write "personal names" in small letters like

https://github.com/ClapeyronThermo/Clapeyron.jl/blob/529af13b80647402253f97af317d1be9e851ba09/docs/src/user_guide/custom_methods.md?plain=1#L47

or

https://github.com/ClapeyronThermo/Clapeyron.jl/blob/529af13b80647402253f97af317d1be9e851ba09/docs/src/properties/basic.md?plain=1#L19

Is that on purpose?

**Comment by longemen3000** [comment]
> Is that on purpose? 
No haha, feel free to correct those docs.

**Comment by Mo-Gul** [comment]
Ok, one more thing I have noticed. Have a look at the items in https://clapeyronthermo.github.io/Clapeyron.jl/dev/user_guide/custom_methods/#Definitions

which is the output of

https://github.com/ClapeyronThermo/Clapeyron.jl/blob/529af13b80647402253f97af317d1be9e851ba09/docs/src/user_guide/custom_methods.md?plain=1#L8-L10

I am guessing that the starts of the lines should look something similar to

```md
[`volume(model, p, T, z)`](@ref)
```

right? But I don't have a clue if this gives the expected result.

**Comment by longemen3000** [comment]
> I am guessing that the starts of the lines should look something similar to

i just checked the docs for Documenter.jl, and the correct syntax for those cases is actually:
```
[volume(model,p,T,z](@ref Clapeyron.volume)
```
https://documenter.juliadocs.org/stable/man/syntax/#Named-@refs

**Comment by Mo-Gul** [comment]
I'd say this is something for another PR which I leave up for you, just in case this doesn't work (directly). Are you fine with that?

**Comment by longemen3000** [comment]
yeah, i will test if that works later. in the meantime, i think this PR is ready to merge.

**Comment by pw0908** [comment]
Mind if I take a look before merging?

**Comment by pw0908** [comment]
@Mo-Gul thanks a lot for all of this! I looked over your modifications and have no issues with any of them.

If it is of interest to you, we are modifying the docs over on a separate [branch](https://github.com/ClapeyronThermo/Clapeyron.jl/tree/docs-update). Progress has been slow, but we'd be grateful for any feedback you might provide!

**Comment by Mo-Gul** [comment]
Sure, but since I just forked the master branch it would be nice to first merge this PR. After that I'll refork and have a look.

Shall I start a discussion for general things about the docs or what would be a proper place for that?

**Comment by pw0908** [comment]
Done!

Discussion would probably be the best place for it.

**Pull request merged**
