### PR TITLE
Implementation of polar SAFT-VR Mie

### PR DESCRIPTION
**Pull request by sonjaamsmith**
Addition of the Gross and Vrabec dipole (2006), quadrupole (2005), and dipole-quadrupole (2008) terms to the SAFT-VR Mie framework as implemented by Cripwell et al. (2018) and Smith et al. (2020).

### CODE REVIEW

**Comment by longemen3000** [comment]
Nice!
- There is a bunch of files named `singledata_EOS` for UNIFAC, PR, and PCSAFT, that are unused, maybe delete those?
- can you add a test checking if the EoS gives a reasonable result?

@pw0908 any comments?

**Comment by pw0908** [comment]
@longemen3000 One thing @sonjaamsmith pointed out is that we use the Hudson-McCoubrey combining rule instead of the sqrt version in SAFT-VR Mie. Do you remember why we did this? I seem to recall we had a conversation about this a long time ago but can't remember why we didn't change it.

**Comment by pw0908** [comment]
Found the relevant issue; it's an outstanding mistake. We switched it for SAFT-gamma Mie but not VR Mie

**Comment by sonjaamsmith** [comment]
I removed those unused files and added a test.

**Review by longemen3000 — APPROVED** [review]

**Comment by pw0908** [comment]
Was about to commit the fix to SAFT-VR mie but it's now been added to master

**Pull request merged**
