### PR TITLE
Unify all Single Empiric Helmoltz models under one struct

### PR DESCRIPTION
**Pull request by longemen3000**
At the moment, we have IAPWS95, PropaneRef, Thol's LJ (LJRef), and now Ammonia 2023. of course, all those models are specific instances of a Multiparameter single fluid. this PR:
- uses the new EoSModel, `EmpiricSingleFluid`, instead of each respective struct
- replaces IAPWS95, PropaneRef, the unscaled part of LJRef (from now onwards TholLJ), and the upcoming Ammonia2023
- adds a parser for JSON files in CoolProp format, that generates `EmpiricSingleFluid` models. the parser can be called via `SingleFluid(component::String; userlocations =String[])`
Parsing all the current files in CoolProp, those are the available terms format:

### Ideal models:
- `IdealGasHelmholtzLead` done
- `IdealGasHelmholtzLogTau` done
- `IdealGasHelmholtzPlanckEinstein` done, it is transformed to generalized einstein
- `IdealGasHelmholtzEnthalpyEntropyOffset` done, same as Lead
- `IdealGasHelmholtzPower` done
- `IdealGasHelmholtzPlanckEinsteinGeneralized` done
- `IdealGasHelmholtzCP0PolyT` done, transformed to a combination of lead, logtau and power terms
- `IdealGasHelmholtzCP0AlyLee` #not done, only n-Heptane and D6 have it, only 5 terms
- `IdealGasHelmholtzCP0Constant` done, transformed to a combination of lead and logtau terms

### residual models:
- `ResidualHelmholtzPower` done
- `ResidualHelmholtzGaussian` done
- `ResidualHelmholtzGaoB` done
- `ResidualHelmholtzNonAnalytic` done, only water have it, maybe optimize the heck out of it?
- `ResidualHelmholtzExponential` done
- `ResidualHelmholtzAssociating` done
- `ResidualHelmholtzLemmon2005` not done, only R125 have it.

the ancilliaries are handled by our `CompositeModel` infraestructure, so if models are missing, it is just a matter of adding those. at the moment we only use the saturation pressure, vapour density and liquid density ancilliaries. 

Ideal models are of the type `IdealEmpiricSingleFluid` . they are generated from the fields of `EmpiricSingleFluid` with no cost.

Another thing is bothering me is the coolprop files, i don't know if do we want (or can) ship those or get those from a predetermined location. ideally, i would like to use something an already existent instalation of CoolProp and get Clapeyron to automatically recognize said location. we can use our current database shortcut format to store:

```
Clapeyron.SHORT_PATHS["COOLPROP"] = "path/to/files"
SingleFluid("water",userlocations = ["@COOLPROP/water.json"])
```

solves #110, #111

### CODE REVIEW

**Comment by longemen3000** [comment]
@ianhbell , about the coolprop files, what do you recommend?

**Comment by ianhbell** [comment]
> @ianhbell , about the coolprop files, what do you recommend?

I would recommend that you import CoolProp via Python, and then get the JSON data for a fluid from the Python interface. There is also this Julia package: https://github.com/CoolProp/CoolProp.jl but I don't think it is feature complete to expose the necessary function (``get_fluid_param_string``)

**Comment by longemen3000** [comment]
> There is also this Julia package: https://github.com/CoolProp/CoolProp.jl but I don't think it is feature complete to expose the necessary function (get_fluid_param_string)
actually, the julia library uses the shared library, so some direct access can be done:
```
using CoolProp #load CoolProp.jl
using Base.Libc.Libdl #dynamic linker std
handle = Libdl.dlopen("libcoolprop") #pointer to lib
dlsym(handle,:get_fluid_param_string) #pointer to method (exists)
```

**Comment by longemen3000** [comment]
Some updates:
 i got a design on Multiparameter fluids that is really similar to that of the cubics. we have two different parameters that can be conjugated: the mixing model (responsible of obtaining delta and tau) and the departure model. 

For example, GERG2008 is a `EmpiricMultifluid{(TypeOfAncillaries),AsymetricMixing,EmpiricDeparture}`. it will be the default for MultiFluid models.

We can use other departures. for example, this paper uses [activity coefficients as departure](https://doi.org/10.1021/acs.iecr.1c01186?rel=cite-as&ref=PDF&jav=VoR). in particular, that paper uses `LinearMixing` + `GEDeparture` (implemented, missing docs). Association can also be plugged (theoretically, is there any group doing that?)

**Comment by pw0908** [comment]
Found a bug:
```julia
julia> MultiFluid(["methanol","water"])
MultiFluid{EmpiricAncillary, AsymmetricMixing, EmpiricDeparture} with 2 components:
 "methanol"
 "water"
Contains parameters: Mw, Tc, Pc, Vc, acentricfactor, lb_volume

julia> volume(model,1e5,298.15,[0.5,0.5])
ERROR: ArgumentError: Collection has multiple elements, must contain exactly 1 element
Stacktrace:
  [1] only
    @ ./iterators.jl:1411 [inlined]
  [2] eos_res(model::SingleFluid{EmpiricAncillary}, V::ForwardDiff.Dual{ForwardDiff.Tag{Clapeyron.var"#fAᵣ#198"{SingleFluid{EmpiricAncillary}, Float64, Vector{Float64}}, ForwardDiff.Dual{ForwardDiff.Tag{Clapeyron.var"#fAᵣ#198"{SingleFluid{EmpiricAncillary}, Float64, Vector{Float64}}, Float64}, Float64, 1}}, ForwardDiff.Dual{ForwardDiff.Tag{Clapeyron.var"#fAᵣ#198"{SingleFluid{EmpiricAncillary}, Float64, Vector{Float64}}, Float64}, Float64, 1}, 1}, T::Float64, z::Vector{Float64})
    @ Clapeyron ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/models/EmpiricHelmholtz/SingleFluid/SingleFluid.jl:218
  [3] fAᵣ
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/VT.jl:130 [inlined]
  [4] f∂f
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/modules/solvers/ad.jl:40 [inlined]
  [5] f∂f∂2f
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/modules/solvers/ad.jl:54 [inlined]
  [6] second_virial_coefficient_impl
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/VT.jl:131 [inlined]
  [7] second_virial_coefficient
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/VT.jl:124 [inlined]
  [8] volume_virial
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/property_solvers/volume.jl:60 [inlined]
  [9] x0_volume_gas
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/initial_guess.jl:15 [inlined]
 [10] x0_volume(model::SingleFluid{EmpiricAncillary}, p::Float64, T::Float64, z::Vector{Float64}; phase::Symbol)
    @ Clapeyron ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/initial_guess.jl:40
 [11] volume_impl(model::SingleFluid{EmpiricAncillary}, p::Float64, T::Float64, z::Vector{Float64}, phase::Symbol, threaded::Bool, vol0::Nothing)
    @ Clapeyron ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/property_solvers/volume.jl:148
 [12] #volume#211
    @ ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/property_solvers/volume.jl:118 [inlined]
 [13] volume(model::SingleFluid{EmpiricAncillary}, p::Float64, T::Float64, z::Vector{Float64})
    @ Clapeyron ~/Library/CloudStorage/OneDrive-ImperialCollegeLondon/University/UROP/SAFT_codes/Clapeyron/src/methods/property_solvers/volume.jl:117
 [14] top-level scope
    @ REPL[20]:1
    ```

**Comment by pw0908** [comment]
Same error occurs for HelmAct as well

**Review by pw0908 — APPROVED** [review]

**Pull request merged**
