### PR TITLE
allow passing a `NamedTuple` to userlocations kwarg

### PR DESCRIPTION
**Pull request by longemen3000**
to make building models in the REPL even easier:
```
julia> model = PCSAFT(["a1"],userlocations = (;
        Mw = [1.],
        epsilon = [2.],
        sigma = [3.],
        segment = [4.],
        k = [0.0;;], #matrix
        n_H = [1],
        n_e = [1],
        epsilon_assoc = Dict((("a1","e"),("a1","H")) => 1000.),
        bondvol = Dict((("a1","e"),("a1","H")) => 0.001)))
PCSAFT{BasicIdeal} with 1 component:
 "a1"
Contains parameters: Mw, segment, sigma, epsilon, epsilon_assoc, bondvol
```
how it works?
when passing a named tuple, we perform a less strict parsing of the params, and transform to Single, Pair, Group or StructGroup depending on the shape of the data, or if the function is called from a `GroupParameter`. instead of doing locations -> csv -> tape -> param, we do namedtuple -> tape -> param and special-case when the component info is `nothing`

~~the big TODO here is the association parameters. at the moment, this works for any models that only uses single, pair or group parameters. but on association, this allows for only setting null association and it is hardcoded to `bondvol` and `epsilon_assoc`.~~
Association is done by passing `Dict{NTuple{2,Ntuple{2,String}},T}`. the special casing for `epsilon_assoc` and `bondvol` is still there to allow to set no-assoc models easily.

things to do:
- ~~tests~~
- docs

### CODE REVIEW

**Comment by pw0908** [comment]
I think we need to be careful as to how this is going to be used. It seems that this method only works for the SAFTs (and any EoS that doesn't depend on a sub-model). For a cubic, we may want to simply assemble it from Tc, Pc, and acentric_factor:
```julia
model = PR(["a1"],userlocations = (;
                      Mw = [15.],
                      Tc = [300.],
                      Pc = [1e6],
                      acentric_factor = [0.05]))
```
Those values will need to be communicated to the alpha model. I'd imagine this issue will also hold true for the activity coefficient models.

We can still merge this into master but with some strong caveats.

**Comment by longemen3000** [comment]
> model = PR(["a1"],userlocations = (; Mw = [15.], Tc = [300.], Pc = [1e6], acentric_factor = [0.05]))
for submodels, we use the corresponding `x_userlocations`. in this case, `alpha_userlocations`
```
model = = PR(["a1"],userlocations = (; Mw = [15.], Tc = [300.], Pc = [1e6]), alpha_userlocations = (;, acentricfactor = [0.05]))
```

**Comment by pw0908** [comment]
Oh, cool, perfect then

**Review by pw0908 — APPROVED** [review]

**Comment by pw0908** [comment]
For clarity, shall we rename userlocations to userparams?

**Comment by longemen3000** [comment]
it is possible, but the main reason i reused `userlocations` is that we don't add new keywords. for example, on a cubic, we would need to add:
- `userparams`
- `ideal_userparams`
- `alpha_userparams`
- `translation_userparams`
- `activity_userparams`
- `mixing_userparams`

**Comment by longemen3000** [comment]
related issue: #106

**Comment by pw0908** [comment]
I'm saying we rename userlocations and userparams, not an additional input

**Comment by longemen3000** [comment]
I like the idea, but seems breaking, for 0.5 seems good

**Comment by pw0908** [comment]
Lets open an issue and keep track of the things we want to add in v0.5. For now, we can merge this branch in.

**Pull request merged**
